### ISSUE TITLE
About Version Dropdown and ReadTheDocs

### ISSUE THREAD

**Issue by dchung0741** [danirus/sphinx-nefertiti#27]
Hi! I'm trying to build a project with different versions on ReadTheDocs with the version dropdown feature of the nefertiti theme, but the dropdown at the navigation bar not clickable.

The way I did it was releasing both versions of my doc on ReadTheDocs first.
One called "ABC" and the other "DEF" for example with urls being "https://ABC/" and "https://DEF/" respectively.

Then in `conf.py`, I have:
```
html_theme_options = {
    'display_version': True,
    "style": "blue",
    "versions": [
        ("ABC", "https://ABC/"),
        ("DEF", "https://DEF/"),
    ]
}
```
Here "ABC" and "DEF" are pure text names instead of semantic versioning as it makes more sense in my project to do so.

I'm wondering if the setting in `conf.py` is wrong or it is actually the case that pure text version name is not supported.
Thank you!

**Comment by danirus** [comment]
Hi. The reason why you don't see it is because when hosting in ReadTheDocs, the version dropdown is rendered using their `versions` context variable that they inject. You can see that in the Nefertiti for Sphinx [`version-dropdown.html`](https://github.com/danirus/sphinx-nefertiti/blob/main/sphinx_nefertiti/version-dropdown.html) template. 

See that in the template I distinguish between `versions` (see [line 13](https://github.com/danirus/sphinx-nefertiti/blob/main/sphinx_nefertiti/version-dropdown.html#L13), this is the variable injected by ReadTheDocs), and `theme_versions`, which is the versions you provide within `html_theme_options`. The actual component is produced with JavaScript code, and placed in a file called `doc_versions.js` in the `_build/html/_static` directory.

To add a label to the dropdown button use the `current_version` entry in `html_theme_options`. I have to add it to the documentation. I'm sorry for that. Your `html_theme_options` would look like:

    html_theme_options = {
        'display_version': True,
        "style": "blue",
        "current_version": "latest",
        "versions": [
            ("ABC", "https://ABC/"),
            ("DEF", "https://DEF/"),
        ]
    }
